Kudu.Web/Models/Application.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Kudu.Web.Models
{
    public class Application : IApplication
    {
        public Application()
        {
            SiteUrls = new List<string>();
        }

        public string Name { get; set; }
        public string ServiceUrl
        {
            get
            {
                return ServiceUrls[0];
            }
        }
        public string SiteUrl
        {
            get
            {
                return SiteUrls[0];
            }
        }
        public IList<string> SiteUrls { get; set; }
        public IList<string> ServiceUrls { get; set; }
    }
}

Kudu.Web/Models/ApplicationViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Kudu.Core.Deployment;
using Kudu.Core.SourceControl;
using Kudu.SiteManagement;

namespace Kudu.Web.Models
{
    public class ApplicationViewModel
    {
        public ApplicationViewModel()
        {
        }

        public ApplicationViewModel(IApplication application, ISettingsResolver settingsResolver)
        {
            Name = application.Name;
            SiteUrl = application.SiteUrl;
            SiteUrls = application.SiteUrls;
            ServiceUrl = application.ServiceUrl;
            ServiceUrls = application.ServiceUrls;
            CustomHostNames = settingsResolver.CustomHostNames;
        }

        [Required]
        public string Name { get; set; }
        public string SiteUrl { get; set; }
        public IEnumerable<string> SiteUrls { get; set; }
        public string ServiceUrl { get; set; }
        public IEnumerable<string> ServiceUrls { get; set; }
        public bool CustomHostNames { get; private set; }
        public RepositoryInfo RepositoryInfo { get; set; }
        
        public string GitUrl
        {
            get
            {
                if (RepositoryInfo == null)
                {
                    return null;
                }
                return RepositoryInfo.GitUrl.ToString();
            }
        }

        public IList<DeployResult> Deployments { get; set; }

        public string CloneUrl
        {
            get
            {
                if (RepositoryInfo == null)
                {
                    return null;
                }

                switch (RepositoryInfo.Type)
                {
                    case RepositoryType.Git:
                        return GitUrl;
                }
                return null;
            }
        }
    }
}

Kudu.Web/Controllers/ApplicationController.cs
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Kudu.Client.Infrastructure;
using Kudu.SiteManagement;
using Kudu.Web.Infrastructure;
using Kudu.Web.Models;

namespace Kudu.Web.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IApplicationService _applicationService;
        private readonly KuduEnvironment _environment;
        private readonly ICredentialProvider _credentialProvider;
        private readonly ISettingsResolver _settingsResolver;

        public ApplicationController(IApplicationService applicationService,
                                     ICredentialProvider credentialProvider,
                                     KuduEnvironment environment,
                                     ISettingsResolver settingsResolver)
        {
            _applicationService = applicationService;
            _credentialProvider = credentialProvider;
            _environment = environment;
            _settingsResolver = settingsResolver;
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            ViewBag.showAdmingWarning = !_environment.IsAdmin && _environment.RunningAgainstLocalKuduService;
            base.OnActionExecuting(filterContext);
        }

        public ViewResult Index()
        {
            var applications = (from name in _applicationService.GetApplications()
                                orderby name
                                select name).ToList();

            return View(applications);
        }

        public Task<ActionResult> Details(string slug)
        {
            return GetApplicationView("settings", "Details", slug);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(string name)
        {
            string slug = name.GenerateSlug();

            try
            {
                await _applicationService.AddApplication(slug);

                return RedirectToAction("Details", new { slug });
            }
            catch (SiteExistsException)
            {
                ModelState.AddModelError("Name", "Site already exists");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View("Create");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string slug)
        {
            if (await _applicationService.DeleteApplication(slug))
            {
                return RedirectToAction("Index");
            }

            return HttpNotFound();
        }

        public async Task<ActionResult> Trace(string slug)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            ICredentials credentials = _credentialProvider.GetCredentials();
            var document = await application.DownloadTrace(credentials);
            return View(document);
        }

        public ActionResult Develop(string slug)
        {
            return RedirectToAction("Details", new { slug });
        }

        [HttpPost]
        [ActionName("add-custom-site-binding")]
        public async Task<ActionResult> AddCustomSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.AddLiveSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("remove-custom-site-binding")]
        public async Task<ActionResult> RemoveCustomSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.RemoveLiveSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("add-service-site-binding")]
        public async Task<ActionResult> AddServiceSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.AddServiceSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        [HttpPost]
        [ActionName("remove-service-site-binding")]
        public async Task<ActionResult> RemoveServiceSiteBinding(string slug, string siteBinding)
        {
            IApplication application = _applicationService.GetApplication(slug);

            if (application == null)
            {
                return HttpNotFound();
            }

            _applicationService.RemoveServiceSiteBinding(slug, siteBinding);

            return await GetApplicationView("settings", "Details", slug);
        }

        private async Task<ActionResult> GetApplicationView(string tab, string viewName, string slug)
        {
            var application = _applicationService.GetApplication(slug);

            ICredentials credentials = _credentialProvider.GetCredentials();
            var repositoryInfo = await application.GetRepositoryInfo(credentials);
            var appViewModel = new ApplicationViewModel(application, _settingsResolver);
            appViewModel.RepositoryInfo = repositoryInfo;

            ViewBag.slug = slug;
            ViewBag.tab = tab;
            ViewBag.appName = appViewModel.Name;
            ViewBag.siteBinding = String.Empty;

            ModelState.Clear();

            return View(viewName, appViewModel);
        }
    }
}

Kudu.Web/Views/Application/Create.cshtml
@model Kudu.Web.Models.ApplicationViewModel

@{
    ViewBag.Title = "New Application";
}

@if (!ViewData.ModelState.IsValid)
{ 
<div class="alert alert-error">
@Html.ValidationSummary(true)
</div>
}

@using (Html.BeginForm())
{    
  <fieldset>
    <legend>New Application</legend>
    <div class="control-group">
      @Html.LabelFor(model => model.Name)
      <div class="controls">        
        @Html.EditorFor(model => model.Name)
        @Html.ValidationMessageFor(model => model.Name)
        <p class="help-block">Name of the application</p>
      </div>
    </div>
    <p>
        <input type="submit" value="Create application" class="btn-primary" />
    </p>
  </fieldset>
}

Kudu.Web/Views/Application/Details.cshtml
@using Kudu.Core.SourceControl
@using Kudu.Web.Models
@using Kudu.Web.Infrastructure

@model ApplicationViewModel

@{
    ViewBag.Title = Model.Name;
}

<form class="well form-inline">
    <label class="control-label"><strong>GIT URL</strong></label>
    <input type="input" id="clone-url" name="name" value="@Model.GitUrl" readonly="readonly" />
</form>

<div class="well">
    <div class="control-group">
        <label class="control-label"><strong>Application URL</strong></label>
        <div class="controls">
            <a href="@Model.SiteUrl" target="_blank">@Model.SiteUrl</a>
            <p class="help-block">This is the link to your website.</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><strong>Service URL</strong></label>
        <div class="controls">
            <a href="@Model.ServiceUrl" target="_blank">@Model.ServiceUrl</a>
            <p class="help-block">This is the link to the kudu service.</p>
        </div>
    </div>
</div>

@if (Model.CustomHostNames)
{
    <div class="well">
        <div class="control-group">
            <label class="control-label"><strong>Custom Application Site Bindings</strong></label>
            <p class="help-block">
            Specify additional site bindings for the service site.  Can be of the format 'hostname', 'hostname:port', 'example.org' or 'example.org:port'.
        </p>
            <p class="help-block">
                Protocol is limited to http only and all bindings entered will be set to http.
            </p>

            @if (Model.SiteUrls.Any())
            {

                <table id="custom-site-bindings" class="table">
                    <tr>
                        <th>Protocol</th>
                        <th>Hostname</th>
                        <th>Port</th>
                        <th></th>
                    </tr>
                    @foreach (string siteBinding in Model.SiteUrls.Skip(1))
                    {
                        var uri = new Uri(siteBinding);
                        
                        <tr>
                            <td>@uri.Scheme</td>
                            <td>@uri.Host</td>
                            <td>@uri.Port</td>
                            <td class="actions">
                                <button type="button" class="btn btn-primary" onclick=" removeBinding('@siteBinding', '#removesitebinding') ">Remove</button>
                            </td>
                        </tr>
                    }

                </table>
                
                    using (Html.BeginForm("remove-custom-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { id = "remove-site-binding-form" }))
                    {
                    @Html.Hidden("siteBinding", "", new { id = "removesitebinding" })
                    }

            }
            
            @using (Html.BeginForm("add-custom-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { @class = "form-inline" }))
            {
                <label class="control-label"><strong>Add application site binding</strong></label>           
                @Html.ValidationSummary()
                <span>http://</span> @Html.TextBox("siteBinding", "", new { placeholder = "example.org" })
                <button id="add_sitebinding" type="submit" class="btn btn-primary">Add binding</button>
            }

        </div>
    </div>
    
    <div class="well">
        <div class="control-group">
            <label class="control-label"><strong>Custom Service Site Bindings</strong></label>
            
            <p class="help-block">
            Specify additional site bindings for the service site.  Can be of the format 'hostname', 'hostname:port', 'example.org' or 'example.org:port'.
        </p>
            <p class="help-block">
            Protocol is limited to http only and all bindings entered will be set to http.
            </p>

            @if (Model.ServiceUrls.Any())
            {

                <table id="custom-site-bindings" class="table">
                    <tr>
                        <th>Protocol</th>
                        <th>Hostname</th>
                        <th>Port</th>
                        <th></th>
                    </tr>
                    @foreach (string siteBinding in Model.ServiceUrls.Skip(1))
                    {
                        var uri = new Uri(siteBinding);
                        
                        <tr>
                            <td>@uri.Scheme</td>
                            <td>@uri.Host</td>
                            <td>@uri.Port</td>
                            <td class="actions">
                                <button type="button" class="btn btn-primary" onclick=" removeBinding('@siteBinding', '#removeservicebinding') ">Remove</button>
                            </td>
                        </tr>
                    }

                </table>
                
                using (Html.BeginForm("remove-service-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { id = "remove-site-binding-form" }))
                {
                    @Html.Hidden("siteBinding", "", new { id = "removeservicebinding" })
                }

            }
            
            @using (Html.BeginForm("add-service-site-binding", "Application", new { slug = Model.Name.GenerateSlug() }, FormMethod.Post, new { @class = "form-inline" }))
            {
                <label class="control-label"><strong>Add service site binding</strong></label>           
                @Html.ValidationSummary()
                <span>http://</span> @Html.TextBox("siteBinding", "", new { placeholder = "example.org" })
                <button id="add_sitebinding" type="submit" class="btn btn-primary">Add binding</button>
            }

        </div>
    </div>
    
    <script type="text/javascript">
        function removeBinding(binding, element) {
            if (confirm('Remove the following site binding: ' + binding)) {
                $(element).val(binding).closest('form').submit();
            }
        }
    </script>
}

@using (Html.BeginForm("Delete", "Application", new { slug = Model.Name.GenerateSlug() }))
{ 
    <input type="submit" class="btn-danger btn-large" name="name" value="Delete Application" />
}

Kudu.Web/Views/Application/Develop.cshtml
@model string
@{
    ViewBag.Title = "Develop";
}

Kudu.Web/Views/Application/Editor.cshtml
@using Kudu.Core.SourceControl
@using Kudu.Web.Models

@model ApplicationViewModel
           
@{
    Layout = null;
    ViewBag.Title = "Editor";

    // Set the mode based on if we have the dev site at all
    var mode = Model.DeveloperSiteUrl == null ? 0 : 1;
    
    // Determine if we can create the site
    bool createDevelopmentSite = ViewData.ContainsKey("Clone");

    // Get the url
    string createDevelopmentSiteUrl = Url.Action("create-dev-site", new { slug = Model.Name });
    string webRootUrl = Url.Action("set-webroot", new { slug = Model.Name });
    
    // Create the javascript expression
    string siteManagerInit = String.Format("$.siteManager({{ createDevelopmentSiteUrl: '{0}', setWebRootUrl: '{1}' }})", createDevelopmentSiteUrl, webRootUrl);
    
    // Code mirror modes
    var modeDirectory = new DirectoryInfo(Server.MapPath("~/Components/Editor/codemirror/mode"));
    var jsFiles = modeDirectory.GetFiles("*.js", SearchOption.AllDirectories);
    var cssFiles = modeDirectory.GetFiles("*.css", SearchOption.AllDirectories);

    var fileExplorerTemplate = Server.MapPath("~/Components/FileExplorer/templates.htm");
    var tabManagerTemplate = Server.MapPath("~/Components/TabManager/templates.htm");
    var diffViewerTemplate = Server.MapPath("~/Components/DiffViewer/templates.htm");
}
<!DOCTYPE html>
<html>
<head>
<title></title>

<script src="@Url.Content("~/Scripts/jquery-1.7.min.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Styles/ui-lightness/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.16.custom.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.render.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.hotkeys-patched.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/Editor/codemirror/default-settings.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Components/Editor/codemirror/codemirror.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/Editor/codemirror/codemirror.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/Shared/base.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Components/Shared/icons.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/Shared/icons.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/Shared/utils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/DiffViewer/diffViewer.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/DiffViewer/diffViewer.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/CommitViewer/commitViewer.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/CommitViewer/commitViewer.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Components/NotificationBar/notificationbar.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/NotificationBar/notificationbar.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/SiteManager/siteManager.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/FileSystem/fileSystem.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/TabManager/tabManager.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/TabManager/tabManager.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/Loader/loader.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/FileExplorer/fileExplorer.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/FileExplorer/fileExplorer.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/Editor/editor.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/Console/console.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/Console/console.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/Dialogs/dialogs.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Components/CommandBar/commandbar.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Components/CommandBar/commandBar.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Components/ide/ide.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Components/ide/ide.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.signalR.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/signalR/hubs")" type="text/javascript"></script>

<!-- Templates -->
@Html.Raw(File.ReadAllText(fileExplorerTemplate))
@Html.Raw(File.ReadAllText(tabManagerTemplate))
@Html.Raw(File.ReadAllText(diffViewerTemplate))

@foreach (var file in cssFiles) {
    string url = String.Format("~/Components/Editor/codemirror/mode/{0}/{1}", file.Directory.Name, file.Name);
<link rel="stylesheet" href="@Url.Content(url)" type="text/css" />
}
@foreach (var file in jsFiles) {
    string url = String.Format("~/Components/Editor/codemirror/mode/{0}/{1}", file.Directory.Name, file.Name);
<script src="@Url.Content(url)" type="text/javascript"></script>
}

<script type="text/javascript">
    $(function () {
        $.ide({
            applicationName: '@Model.Name',
            tabManager: $('#tabs'),
            editor: $('#editor'),
            fileExplorer: $('#files'),
            activeView : $('#active-view'),
            launcher : $('#run'),
            projectList : $('#projects'),
            notificationBar : $('#notification-bar'),
            statusBar : $('#status'),
            mode: @mode,
            createDevelopmentSite : @createDevelopmentSite.ToString().ToLower(),
            siteManager: @Html.Raw(siteManagerInit),
            siteUrl: '@Model.SiteUrl'
        });
    });
    </script>
</head>
<body>
    <div id="notification-bar">
    </div>
    <ul id="actions">
        <li>
            <a href="#" class="icon icon-new-file" data-action="new-file">New File</a> 
        </li>
        <li>
            <a href="#" class="icon icon-save" data-action="save-all">Save All</a>
        </li>
        <li>
            <a href="#" class="icon icon-refresh" data-action="refresh-project">Refresh</a>
        </li>
        <li>
            <a href="#" class="icon icon-build dev-mode" data-action="build">Build</a>
        </li>
        <li>            
            <a href="@Model.DeveloperSiteUrl" target="_blank" class="icon icon-run dev-mode" id="run">Run</a>
        </li>
        <li>
            <a href="#" class="icon icon-live dev-mode" data-action="go-live">Go Live</a>
        </li>
        <li class="project-selection dev-mode">
            Projects: <select id="projects"></select>   
        </li>
    </ul>

    <select id="active-view"@if (Model.RepositoryType == RepositoryType.None) {<text> class="hide"</text>}>
        <option value="1">Developer</option>
        <option value="0"@if (Model.RepositoryType == RepositoryType.None) {<text> selected="selected"</text>}>Live</option>
    </select>

    <ul id="tabs">
    </ul>
    <div class="clear"></div>
    <div id="ide">
        <div id="edit-area">
            <textarea id="editor"></textarea>
        </div>
        <div id="files">
        </div>
    </div>
    <div class="clear"></div>
    <div id="status-container">
        <div id="status" class="icon icon-save">
        </div>
    </div>
</body>
</html>

Kudu.Web/Views/Application/Index.cshtml
@using Kudu.Core.SourceControl
@using Kudu.Web.Models
@using Kudu.Web.Infrastructure

@model IEnumerable<string>

@{
    ViewBag.Title = "Applications";
}

<div class="well">
    <ul class="nav nav-list">
        <li class="nav-header">Applications</li>
        @foreach (var item in Model)
        {    
            <li>
                <a href="@Url.RouteUrl("ApplicationDetails", new { slug = item })">
                    <i class="icon-th-list"></i>
                    @item
                </a>
            </li>
        }
    </ul>    
</div>

Kudu.Web/Views/Application/Trace.cshtml
@model XDocument

@using System.Xml
@using System.Xml.Linq

@{
    ViewBag.Title = "Trace";
}

@section head {
    <link href="@Url.Content("~/Styles/trace.css")" rel="stylesheet" type="text/css" />
}

@if (Model != null)
{ 
    @Html.Partial("_TraceView", Model)
}